[package]
name = "jex-core"
version = "0.6.0"
edition = "2021"
description = "jex core library - JVM toolchain logic"
license = "MIT"

[dependencies]
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
crossterm.workspace = true
atty.workspace = true
reqwest.workspace = true
quick-xml.workspace = true
