[package]
name = "jex-core"
version.workspace = true
edition.workspace = true
description = "jex core library - JVM toolchain logic"
license.workspace = true

[dependencies]
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
crossterm.workspace = true
atty.workspace = true
reqwest.workspace = true
quick-xml.workspace = true
dirs.workspace = true
notify.workspace = true

[dev-dependencies]
tempfile.workspace = true
serial_test.workspace = true
